services:
  - type: web
    name: pansheng-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
  - type: web
    name: pansheng-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
